name: CI

# Trigger workflow on pull request or pushes to master branch
on:
  pull_request:
  push:
    branches: [master]

env:
  GOLANGCI_LINT_VERSION: v2.11.3

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          check-latest: true
          go-version-file: "go.mod"
      - uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}

  unittests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    needs:
      - lint
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - macos-15
          - windows-2025
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          check-latest: true
          go-version-file: "go.mod"

      - name: Run tests
        run: |
          go test -v -race "-coverprofile=coverage.txt" ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        if: ${{ matrix.os == 'ubuntu-24.04' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  pre-merge-check:
    runs-on: ubuntu-24.04
    if: always()
    needs:
      - lint
      - unittests
    steps:
      - name: Fail if any required job did not succeed
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        run: exit 1
      - name: All tests passed
        run: echo "All tests passed!"
