name: CI

# Trigger workflow on pull request or pushes to master branch
on:
  pull_request:
  push:
    branches: [master]

env:
  GOLANGCI_LINT_VERSION: v2.11.3

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          check-latest: true
          go-version-file: "go.mod"
      - uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}

  unittests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    needs:
      - lint
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - macos-15
          - windows-2025
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          check-latest: true
          go-version-file: "go.mod"

      - name: Run tests
        run: |
          go test -v -race "-coverprofile=coverage.txt" ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        if: ${{ matrix.os == 'ubuntu-24.04' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  pre-merge-check:
    runs-on: ubuntu-24.04
    if: always()
    needs:
      - lint
      - unittests
    steps:
      - name: Fail if any required job did not succeed
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        run: exit 1
      - name: All tests passed
        run: echo "All tests passed!"
