name: Build and Release
run-name: Release ${{ github.ref_name }}

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-24.04
    permissions:
        contents: write
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name:  ${{ github.ref_name }}
          body: |
            ## Release Notes

            For information about changes in this release see the [changelog](https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}/CHANGELOG.md).
